// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/aboutus.tsx";
import * as $3 from "./routes/api/login.ts";
import * as $4 from "./routes/api/logout.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/loginpage.tsx";
import * as $$0 from "./islands/signUp.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/aboutus.tsx": $2,
    "./routes/api/login.ts": $3,
    "./routes/api/logout.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/loginpage.tsx": $6,
  },
  islands: {
    "./islands/signUp.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
